# Generated by Django 4.1.4 on 2022-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
